container:
  image: node:8

lint_task:      
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  
  env:
    HOST: '0.0.0.0'
    PORT: 3000
    COMUNI_JSON_FILE: comuni.json

  test_script: npm run lint

test_task:
  
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install

  env:
    HOST: '0.0.0.0'
    PORT: 3000
    COMUNI_JSON_FILE: comuni.json

  test_script: npm run test test/01_updateComuni.js && npm run test test/02_routes.js
