container:
  image: node:8

lint_task:      
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  
  env:
    HOST: '0.0.0.0'
    PORT: 3000
    COMUNI_JSON_FILE: comuni.json

  test_script: npm run lint

test_task:

  only_if: $CIRRUS_BRANCH != 'master'
  
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install

  env:
    HOST: '0.0.0.0'
    PORT: 3000
    COMUNI_JSON_FILE: comuni.json

  test_script: npm run test

cover_task:
  
  only_if: $CIRRUS_BRANCH == 'master'

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install

  env:
    HOST: '0.0.0.0'
    PORT: 3000
    COMUNI_JSON_FILE: comuni.json
    COVERALLS_REPO_TOKEN: ENCRYPTED[8dca0807d4d5d09f6e57b485c3426a843e97c71d83f74469199943389ed50e925b52206a77ffc5be328c12387304c7d6]

  test_script: npm run cover
